// examples/vue-datastore/src/components/Todo/TodoList.tsx
import { computed, defineComponent, h, PropType } from "vue";
import { Todo } from "../../datastore/generated";
import { Empty } from "../UI";
import { TodoItem } from "./TodoItem";

export const TodoList = defineComponent({
  props: {
    todos: {
      type: Array as PropType<Todo[]>,
      required: true,
      default: () => [],
    },
  },
  components: {
    TodoItem,
    Empty,
  },
  setup(props) {
    const noTodos = computed(() => !props.todos || props.todos.length === 0);
    return () =>
      h("div", {}, [
        noTodos.value ? h(<empty />) : null,
        ...props.todos.map((todo) =>
          h(
            <a-card key={todo._id} style='margin: "0.5em 0"'>
              <todo-item todo={todo} />
            </a-card>
          )
        ),
      ]);
  },
});

// examples/react-datastore/src/components/TodoList.jsx
import React from 'react';
import { useEditTodo, useDeleteTodo } from '../hooks';
import { Empty } from './Empty';
import { Todo } from './Todo/Todo';

export const TodoList = ({ todos }) => {
  const { editTodo } = useEditTodo();
  const { deleteTodo } = useDeleteTodo();

  if (todos.length === 0) return <Empty />;

  return (
    <>
      {
        // map through todos and render
        // each todo item
        todos && todos.map((todo) => (
          <div key={todo.id} className="card" style={{ margin: ' 0.5em 1em' }}>
            <div className="card-body">
              <div className="container">
                <Todo
                  todo={todo}
                  editTodo={editTodo}
                  deleteTodo={deleteTodo}
                />
              </div>
            </div>
          </div>
        ))
      }
    </>
  );
};
