// examples/react-datastore/src/components/forms/AddTodo.tsx
import { Button } from "antd";
import React from "react";
import { AutoForm, LongTextField, SubmitField, TextField } from "uniforms-antd";
import { Todo } from "../../datastore/generated";
import { useAddTodo } from "../../datastore/hooks";
import { AddTodoProps } from "../../types";
import { schema } from "./formSchema";

export const AddTodo = ({ cancel }: AddTodoProps) => {
  const { save: addTodo, data, loading, error } = useAddTodo();

  const handleSubmit = ({ title, description }: Todo) => {
    addTodo({
      title,
      description,
      completed: false,
    })
      .then(() => {
        console.log({ data, loading, error });

        cancel();
      })
      .catch((error: any) => console.log(error));
  };

  return (
    <AutoForm
      className="ant-form-vertical"
      schema={schema}
      onSubmit={handleSubmit}
    >
      <TextField name="title" />
      <LongTextField name="description" />
      <Button onClick={cancel}>Cancel</Button>
      <SubmitField style={{ float: "right" }} />
    </AutoForm>
  );
};

// examples/vue-datastore/src/components/forms/AddTodo.vue
<template>
  <a-col class="ant-form-vertical">
    <a-input v-model:value="title" name="title" />
    <a-textarea name="description" v-model:value="description" auto-size />
    <a-button @click="cancel()">Cancel</a-button>
    <a-button @click="handleSubmit" style="float: 'right'">Submit</a-button>
  </a-col>
</template>
<script lang="ts">
import { defineComponent, ref } from "vue";
import { useAddTodo } from "../../datastore/hooks";

export default defineComponent({
  name: "AddTodo",
  props: {
    cancel: {
      type: Function,
      required: true,
    },
  },
  setup(props) {
    const { save: addTodo } = useAddTodo();

    const title = ref("");
    const description = ref("");

    const handleSubmit = () => {
      addTodo({
        title: title.value,
        description: description.value,
        completed: false,
      })
        .then(() => props.cancel())
        .catch((error: any) => console.log(error));
    };
    return { title, description, handleSubmit };
  },
});
</script>
