// examples/react/src/components/forms/ToggleTodo.tsx
import React from 'react';
import { QuickForm, BoolField } from 'uniforms-antd';
import { useOfflineMutation } from 'react-offix-hooks';

import { ToggleTodoProps } from "../../types";
import { schema } from '../../config/formSchema';
import { EDIT_TODO } from '../../gql/queries';
import { mutateOptions } from '../../helpers';

export function ToggleTodo ({ todo }: ToggleTodoProps) {

  const [editTodo] = useOfflineMutation(EDIT_TODO, mutateOptions.edit);

  const handleUpdate = () => {
    editTodo({
      variables: {
        ...todo,
        completed: !todo.completed,
      },
    }).then(res => console.log(res))
    .catch(error => console.log(error));
  };

  return(
    <QuickForm schema={schema}>
      <BoolField 
        label={todo.title}
        value={todo.completed}
        onChange={handleUpdate}
        name="completed" 
      />
    </QuickForm>
  );
}

// examples/vue-datastore/src/components/forms/ToggleTodo.vue
<template>
  <a-row>
    <a-switch v-model:checked="checked" />
    {{ label }}
  </a-row>
</template>
<script lang="ts">
import { Todo } from "../../datastore/generated";
import { computed, defineComponent, PropType } from "vue";
import { useEditTodo } from "../../datastore/hooks";
export default defineComponent({
  name: "ToggleTodo",
  props: {
    todo: {
      type: Object as PropType<Todo>,
      required: true,
    },
  },
  setup(props) {
    const { update: updateTodo } = useEditTodo();

    const handleUpdate = (completed: boolean) => {
      updateTodo({
        ...props.todo,
        _version: props.todo._version ?? 1,
        completed: completed,
      })
        .then((res) => console.log("response", res))
        .catch((error: any) => console.log("error", error));
    };
    const checked = computed({
      set: (complited) => {
        handleUpdate(complited);
      },
      get: () => props.todo.completed ?? false,
    });
    return { label: props.todo.title, checked };
  },
});
</script>
