// examples/vue-datastore/src/components/forms/ToggleTodo.vue
<template>
  <a-row>
    <a-switch v-model:checked="checked" />
    {{ label }}
  </a-row>
</template>
<script lang="ts">
import { Todo } from "../../datastore/generated";
import { computed, defineComponent, PropType } from "vue";
import { useEditTodo } from "../../datastore/hooks";
export default defineComponent({
  name: "ToggleTodo",
  props: {
    todo: {
      type: Object as PropType<Todo>,
      required: true,
    },
  },
  setup(props) {
    const { update: updateTodo } = useEditTodo();

    const handleUpdate = (completed: boolean) => {
      updateTodo({
        ...props.todo,
        _version: props.todo._version ?? 1,
        completed: completed,
      })
        .then((res) => console.log("response", res))
        .catch((error: any) => console.log("error", error));
    };
    const checked = computed({
      set: (complited) => {
        handleUpdate(complited);
      },
      get: () => props.todo.completed ?? false,
    });
    return { label: props.todo.title, checked };
  },
});
</script>

// examples/react-datastore/src/components/forms/ToggleTodo.tsx
import React from 'react';
import { QuickForm, BoolField } from 'uniforms-antd';

import { ToggleTodoProps } from "../../types";
import { schema } from './formSchema';
import { useEditTodo } from '../../datastore/hooks';

export function ToggleTodo({ todo }: ToggleTodoProps) {

  const { update: editTodo } = useEditTodo();

  const handleUpdate = () => {
    editTodo({
      ...todo,
      _version: todo._version ?? 1,
      completed: !todo.completed,
    })
      .then((res: any) => console.log("response", res))
      .catch((error: any) => console.log("error", error));
  };

  return (
    <QuickForm schema={schema}>
      <BoolField
        label={todo.title}
        value={todo.completed}
        onChange={handleUpdate}
        name="completed"
      />
    </QuickForm>
  );
}
