// examples/vue-datastore/src/components/forms/AddTodo.vue
<template>
  <a-col class="ant-form-vertical">
    <a-input v-model:value="title" name="title" />
    <a-textarea name="description" v-model:value="description" auto-size />
    <a-button @click="cancel()">Cancel</a-button>
    <a-button @click="handleSubmit" style="float: 'right'">Submit</a-button>
  </a-col>
</template>
<script lang="ts">
import { defineComponent, ref } from "vue";
import { useAddTodo } from "../../datastore/hooks";

export default defineComponent({
  name: "AddTodo",
  props: {
    cancel: {
      type: Function,
      required: true,
    },
  },
  setup(props) {
    const { save: addTodo } = useAddTodo();

    const title = ref("");
    const description = ref("");

    const handleSubmit = () => {
      addTodo({
        title: title.value,
        description: description.value,
        completed: false,
      })
        .then(() => props.cancel())
        .catch((error: any) => console.log(error));
    };
    return { title, description, handleSubmit };
  },
});
</script>

// examples/react/src/components/forms/AddTodo.tsx
import React from 'react';
import { Button } from 'antd';
import { 
  AutoForm, 
  TextField, 
  LongTextField, 
  HiddenField, 
  SubmitField 
} from 'uniforms-antd';
import { useOfflineMutation } from 'react-offix-hooks';

import { AddTodoProps, ITodo } from '../../types';
import { schema } from '../../config/formSchema';
import { mutateOptions } from '../../helpers';
import { ADD_TODO } from '../../gql/queries';

export const AddTodo = ({ cancel }: AddTodoProps) => {

  const [addTodo] = useOfflineMutation(ADD_TODO, mutateOptions.add);

  const handleSubmit = ({ title, description, completed }: ITodo) => {
    addTodo({
      variables: {
        title,
        description,
        completed,
      },
    })
    .then(() => cancel())
    .catch((error: any) => {
      console.log(error);
      if (error.offline) {
        cancel();
      }
    });
  };

  return (
    <AutoForm className='ant-form-vertical' schema={schema} onSubmit={handleSubmit}>
      <TextField name="title" />
      <LongTextField name="description" />
      <HiddenField name="completed" value={false} />
      <Button onClick={cancel}>Cancel</Button>
      <SubmitField style={{ float: 'right' }} />
    </AutoForm>
  );
};
